/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SampleContractInterface extends Interface {
    getFunction(nameOrSignature: "dumbValue" | "fireSampleEvent"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "SampleEvent"): EventFragment;

    encodeFunctionData(functionFragment: 'dumbValue', values?: undefined): string;
encodeFunctionData(functionFragment: 'fireSampleEvent', values: [BytesLike, BigNumberish, BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'dumbValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fireSampleEvent', data: BytesLike): Result;
  }

  
    export namespace SampleEventEvent {
      export type InputTuple = [foo: BytesLike, bar: BigNumberish, baz: BigNumberish, data: string];
      export type OutputTuple = [foo: string, bar: bigint, baz: bigint, data: string];
      export interface OutputObject {foo: string, bar: bigint, baz: bigint, data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SampleContract extends BaseContract {
    
    connect(runner?: ContractRunner | null): SampleContract;
    waitForDeployment(): Promise<this>;

    interface: SampleContractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    dumbValue: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    fireSampleEvent: TypedContractMethod<
      [foo: BytesLike, bar: BigNumberish, baz: BigNumberish, data: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'dumbValue'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'fireSampleEvent'): TypedContractMethod<
      [foo: BytesLike, bar: BigNumberish, baz: BigNumberish, data: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'SampleEvent'): TypedContractEvent<SampleEventEvent.InputTuple, SampleEventEvent.OutputTuple, SampleEventEvent.OutputObject>;

    filters: {
      
      'SampleEvent(bytes32,uint256,int256,string)': TypedContractEvent<SampleEventEvent.InputTuple, SampleEventEvent.OutputTuple, SampleEventEvent.OutputObject>;
      SampleEvent: TypedContractEvent<SampleEventEvent.InputTuple, SampleEventEvent.OutputTuple, SampleEventEvent.OutputObject>;
    
    };
  }